const $=s=>document.querySelector(s), state={cases:[],distribution_cycles:[]};
const toast=message=>{const e=$('#toast');e.textContent=message;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3500)};
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const v=await r.json();if(!r.ok)throw Error(v.error||'Request failed');return v}
function esc(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function title(value=''){return value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
async function refresh(){Object.assign(state,await api('/api/state'));$('#case-count').textContent=`${state.cases.length} case${state.cases.length===1?'':'s'}`;$('#system-status').textContent=`Pioneer ${state.pioneer_configured?'ready':'not configured'} / Resend ${state.email_configured?'ready':'not configured'} / Linq ${state.linq_configured?'ready':'not configured'} / Terac ${state.terac_configured?'ready':'not configured'}`;renderCases();renderCycles()}
function renderCases(){const el=$('#cases');if(!state.cases.length){el.className='list empty';el.textContent='No cases yet.';return}el.className='list';el.innerHTML=state.cases.map(c=>`<button class="case-card" data-id="${c.id}"><span><strong>${esc(c.tenant)}</strong>${c.synthetic?'Synthetic evaluation':'Customer case'}</span><b class="badge ${c.state==='failed_closed'?'bad':''}">${title(c.state)}</b></button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>showCase(b.dataset.id))}
async function showCase(id){const c=await api(`/api/cases/${id}`),d=c.data,r=d.result,a=r?.audit,detail=$('#case-detail');detail.classList.remove('hidden');detail.innerHTML=`<div class="panel-head"><div><h2>${esc(c.tenant)}</h2><span>${c.synthetic?'Clearly labeled synthetic evaluation':'Customer case'} / ${esc(c.email)}</span></div><b class="badge ${c.state==='failed_closed'?'bad':a?'good':''}">${title(c.state)}</b></div><div class="detail-grid"><aside class="timeline"><p class="eyebrow">Evidence ledger</p>${c.events.map(e=>`<div class="timeline-item"><strong>${esc(e.trigger)}</strong><span>${esc(e.actor)} / ${new Date(e.created_at).toLocaleString()}</span><span>${esc(e.acceptance_decision)}</span></div>`).join('')}</aside><div>${d.eligibility.eligible?'<p class="badge good">Eligible / $499 managed case</p>':`<p class="badge bad">Not eligible</p><p>${d.eligibility.reasons.map(esc).join('<br>')}</p>`}<div class="actions">${c.state==='intake_incomplete'?'<button class="primary" data-action="audit">Run verified audit</button>':''}${c.state==='waiting_for_customer_consent'?'<button class="primary" data-action="authorize">Authorize and sign notice</button>':''}${['notice_sent','waiting_for_landlord_reply','escalation_approved'].includes(c.state)&&d.landlord_phone?'<button class="primary" data-action="followup">Send Linq follow-up</button>':''}${d.eligibility.eligible?'<button class="quiet" data-action="pay">Open checkout</button>':''}</div>${a?`<div class="panel-head"><h2>Verified result</h2><strong>${a.outcome_if_accepted==='credit'?`$${Math.abs(Number(a.verified_balance)).toFixed(2)} credit`:`$${Number(a.verified_balance).toFixed(2)} corrected bill`}</strong></div><p>Deadline: <strong>${a.deadline.value}</strong> / Correction: <strong>$${Number(a.correction).toFixed(2)}</strong></p>${a.findings.map(f=>`<article class="finding"><div class="finding-head"><strong>${esc(f.title)}</strong><b>$${Number(f.amount).toFixed(2)}</b></div><p>${esc(f.lease_evidence.document)} ${esc(f.lease_evidence.location)}: “${esc(f.lease_evidence.quote)}”</p><p>${esc(f.calculation)}</p></article>`).join('')}<h2>Formal notice</h2><pre class="notice">${esc(r.draft_notice)}</pre>`:''}</div></div>`;detail.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>caseAction(c,b.dataset.action));detail.scrollIntoView({behavior:'smooth',block:'start'})}
async function caseAction(c,verb){try{let payload={};if(verb==='authorize'){const name=prompt('Type the authorized signer name.');if(!name)return;await api(`/api/cases/${c.id}/authorize`,{method:'POST',body:JSON.stringify({name,records_requests:true,communications:true})});payload={name,attested:confirm('I attest that I can sign this tenant notice. Continue?')};if(!payload.attested)return;verb='sign'}const value=await api(`/api/cases/${c.id}/${verb}`,{method:'POST',body:JSON.stringify(payload)});if(verb==='pay'){const action=value.actions.at(-1);const p=JSON.parse(action.payload);window.open(p.url,'_blank','noopener')}await refresh();await showCase(c.id)}catch(e){toast(e.message);await refresh()}}
$('#demo').onclick=async()=>{try{const v=await api('/api/demo',{method:'POST',body:'{}'});await refresh();await showCase(v.id);toast('Synthetic documents loaded. Run the audit to call Kimi K3.')}catch(e){toast(e.message)}};
$('#intake').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type="submit"]'),error=$('#intake-error'),form=new FormData(e.target),files=form.getAll('documents'),documents=[];error.textContent='';button.disabled=true;button.textContent='Checking case';for(const file of files){const kind=/lease/i.test(file.name)?'lease':/recon|cam/i.test(file.name)?'reconciliation':/ledger|payment/i.test(file.name)?'ledger':'other',bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));documents.push({kind,name:file.name,base64:btoa(binary)})}try{const payload=Object.fromEntries(form);payload.documents=documents;const v=await api('/api/cases',{method:'POST',body:JSON.stringify(payload)});e.target.reset();await refresh();await showCase(v.id)}catch(err){error.textContent=err.message;toast(err.message)}finally{button.disabled=false;button.textContent='Check eligibility'}};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const name=b.dataset.view;document.querySelectorAll('[data-view]').forEach(item=>item.classList.toggle('active',item===b));$('#cases-view').classList.toggle('hidden',name!=='cases');$('#distribution-view').classList.toggle('hidden',name!=='distribution')});
function renderCycles(){const el=$('#cycles');el.innerHTML=state.distribution_cycles.length?state.distribution_cycles.map(c=>{const d=c.data;return `<article class="panel cycle"><p class="eyebrow">${esc(c.status)} / ${new Date(c.created_at).toLocaleString()}</p><h2>${esc(d.target)}</h2><p><strong>${title(d.channel)}</strong></p><p>${esc(d.hypothesis)}</p><p><strong>Human job</strong><br>${esc(d.human_job)}</p><div class="metric"><div><strong>${d.qualified_prospects||0}</strong>Qualified</div><div><strong>${d.paid_cases||0}</strong>Paid cases</div></div></article>`}).join(''):'<div class="panel"><p>No cycle exists. The manager will select its first target, channel, and human job from policy.</p></div>'}
$('#new-cycle').onclick=async()=>{try{const v=await api('/api/distribution/cycles',{method:'POST',body:'{}'});await refresh();toast(`Manager selected ${v.channel}.`)}catch(e){toast(e.message)}};
refresh().catch(e=>toast(e.message));
